Repository LuckyVickys/woosan-back, pull requests merged in 2024-06, with the labels that each got.

#2 feat: Board entity 생성
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Board.java
Labels: 💾 Server, ✨ Feature

#3 build: mybatis 설정
  build.gradle
  src/main/java/com/luckyvicky/woosan/domain/board/mapper/BoardMapper.java
  src/main/java/com/luckyvicky/woosan/domain/boardLikes/mapper/BoardLikesMapper.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/mapper/FileImgMapper.java
  src/main/java/com/luckyvicky/woosan/domain/matchingBoard/mapper/MatchingBoardMapper.java
  src/main/java/com/luckyvicky/woosan/domain/matchingBoardReply/mapper/MatchingBoardReplyMapper.java
  src/main/java/com/luckyvicky/woosan/domain/member/mapper/MemberMapper.java
  src/main/java/com/luckyvicky/woosan/domain/memberMatching/mapper/MemberMatchingMapper.java
  src/main/java/com/luckyvicky/woosan/domain/memberProfile/mapper/MemberProfileMapper.java
  src/main/java/com/luckyvicky/woosan/domain/messages/mapper/MessagesMapper.java
  src/main/java/com/luckyvicky/woosan/domain/myPage/controller/MyPageController.java
  src/main/java/com/luckyvicky/woosan/domain/myPage/dto/MyPageDTO.java
  src/main/java/com/luckyvicky/woosan/domain/myPage/entity/MyPage.java
  src/main/java/com/luckyvicky/woosan/domain/myPage/mapper/MyPageMapper.java
  src/main/java/com/luckyvicky/woosan/domain/myPage/repository/MyPageRepository.java
  src/main/java/com/luckyvicky/woosan/domain/myPage/service/MyPageService.java
  src/main/java/com/luckyvicky/woosan/domain/myPage/service/MyPageServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/reply/mapper/ReplyMapper.java
  src/main/java/com/luckyvicky/woosan/domain/replyLikes/mapper/ReplyLikesMapper.java
  src/main/java/com/luckyvicky/woosan/domain/report/mapper/ReportMapper.java
Labels: 💾 Server, ⚙ Setting

#4 feat: member entity 생성
  src/main/java/com/luckyvicky/woosan/domain/member/entity/Member.java
Labels: 💾 Server, ✨ Feature

#6 fix: gitignore에 QueryDsl Q클래스 커밋 방지 코드 작성
  .gitignore
Labels: 💾 Server, 🔨 Fix, ⚙ Setting

#7 MyPage Entity 생성
  src/main/java/com/luckyvicky/woosan/domain/myPage/entity/MyPage.java
Labels: 💾 Server

#8 fix: memberEntity 오류나는 값 수정
  src/main/java/com/luckyvicky/woosan/domain/member/entity/Member.java
  src/main/java/com/luckyvicky/woosan/domain/myPage/entity/MyPage.java
Labels: 🐞 BugFix, 💾 Server, 🔨 Fix

#9 fix: gitignore, member entity
  .gitignore
  src/main/java/com/luckyvicky/woosan/domain/member/entity/Member.java
Labels: 💾 Server, 🔨 Fix, ⚙ Setting

#11 feat: SpringSecurity를 위한 MemberType 생성
  src/main/java/com/luckyvicky/woosan/domain/member/entity/MemberType.java
Labels: 💾 Server, ✨ Feature

#16 fix: level 필드와 생성자 추가
  src/main/java/com/luckyvicky/woosan/domain/member/entity/Member.java
Labels: 💾 Server, 🔨 Fix

#17 feat: Member, MemberProfile, MemberType, SocialType enum, MBTI enum 생성
  build.gradle
  src/main/java/com/luckyvicky/woosan/domain/member/entity/MBTI.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/Member.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/MemberProfile.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/MemberType.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/SocialType.java
Labels: 💾 Server, ✨ Feature, 🔨 Fix

#18 Feat/fileupload
  build.gradle
  src/main/java/com/luckyvicky/woosan/domain/fileImg/controller/FileImgController.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/entity/FileImg.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/mapper/FileImgMapper.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/repository/FileImgRepository.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgService.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgServiceImpl.java
  src/test/java/com/luckyvicky/woosan/testServcie/FileImgServiceTests.java
  src/test/java/com/luckyvicky/woosan/testrepository/fileImg/FileImgTests.java
Labels: 💾 Server, ✅ Test

#19 test: addMember test 코드
  src/test/java/com/luckyvicky/woosan/repository/MemberRepositoryTests.java
Labels: 💾 Server, ✅ Test

#24 Feat/report domain
  src/main/java/com/luckyvicky/woosan/domain/report/dto/ReportDTO.java
  src/main/java/com/luckyvicky/woosan/domain/report/entity/Report.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportService.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportServiceImpl.java
  src/test/java/com/luckyvicky/woosan/testService/ReportServiceTests.java
Labels: 🐞 BugFix, 💾 Server, 🔨 Fix, ✅ Test

#20 feat: email 중복 확인
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberController.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/MemberRepository.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API

#21 Feat: nickname 중복 체크
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberController.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/MemberRepository.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API

#28 Feat/board
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardPageResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardWithRepliesDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/PageRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/PageResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/ReplyDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Board.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Reply.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IBoard.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IBoardMember.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IReply.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/MemberInfo.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/ReplyRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/MemberDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/Member.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/MemberRepository.java
  src/main/java/com/luckyvicky/woosan/global/config/RootConfig.java
  src/test/java/com/luckyvicky/woosan/repository/BoardRepositoryTest.java
  src/test/java/com/luckyvicky/woosan/repository/ReplyRepositoryTest.java
  src/test/java/com/luckyvicky/woosan/service/BoardServiceTest.java
  src/test/java/com/luckyvicky/woosan/service/ReplyServiceTest.java
Labels: 💾 Server, ✨ Feature, ✅ Test

#29 fix: email 오류 코드 삭제
  src/test/java/com/luckyvicky/woosan/service/ReplyServiceTest.java
Labels: 💾 Server, 🔨 Fix, ✅ Test

#30 fix/ 작성 시 포인트 추가 메서드(Member entity)
  src/main/java/com/luckyvicky/woosan/domain/member/entity/Member.java
Labels: 💾 Server, ✨ Feature

#31 fix/ 댓글 추천 오류 주석처리
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Reply.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IReply.java
Labels: 🔨 Fix

#32 fix: 비밀번호 암호화 주석
  build.gradle
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
Labels: 💾 Server, 🔨 Fix, ⚙ Setting

#34 Fea/report add
  build.gradle
  src/main/java/com/luckyvicky/woosan/domain/fileImg/controller/FileImgController.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/entity/FileImg.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/repository/FileImgRepository.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgService.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/report/dto/ReportDTO.java
  src/main/java/com/luckyvicky/woosan/domain/report/entity/Report.java
  src/main/java/com/luckyvicky/woosan/domain/report/repository/ReportRepository.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportService.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportServiceImpl.java
  src/test/java/com/luckyvicky/woosan/testServcie/FileImgServiceTests.java
  src/test/java/com/luckyvicky/woosan/testService/ReportServiceTests.java
  src/test/java/com/luckyvicky/woosan/testrepository/fileImg/FileImgTests.java
  src/test/java/com/luckyvicky/woosan/testrepository/report/ReportRepositoryTests.java
Labels: 💾 Server, 🔨 Fix

#37 feat/ board-fix& 조회수 기능 구현
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardWithRepliesDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IBoardMember.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/MemberInfo.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/util/HashUtil.java
Labels: 💾 Server, 🔨 Fix

#35 feat: 게시판등록 사진업로드 기능 추가
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/test/java/com/luckyvicky/woosan/service/BoardServiceTest.java
Labels: 💾 Server, ✨ Feature, ✅ Test

#36 fix: MemberController url 슬래시 누락 추가
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberController.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#38 fix: 테스트클래스 패키징, board 테스트 코드 수정
  src/main/java/com/luckyvicky/woosan/domain/fileImg/entity/FileImg.java
  src/main/java/com/luckyvicky/woosan/domain/likes/entity/Likes.java
  src/test/java/com/luckyvicky/woosan/repository/FileImgTests.java
  src/test/java/com/luckyvicky/woosan/repository/ReportRepositoryTests.java
  src/test/java/com/luckyvicky/woosan/service/BoardServiceTest.java
  src/test/java/com/luckyvicky/woosan/service/FileImgServiceTests.java
Labels: 🐞 BugFix, 🔨 Fix, ✅ Test

#39 Feat/create temp pw
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberController.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/MailDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/UpdatePwDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/Member.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/MemberRepository.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
  src/test/java/com/luckyvicky/woosan/repository/MemberRepositoryTests.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix, ✅ Test

#40 fix: buid.gradle 수정(메일 전송 관련)
  build.gradle
Labels: 💾 Server, 🔨 Fix, ⚙ Setting

#41 feat: matching 엔티티 3개 작성
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoard.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoardReply.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MemberMatching.java
Labels: 💾 Server, ✨ Feature

#42 fix:gradle(S3)
  build.gradle
Labels: 🐞 BugFix

#44 feat: 비밀번호 메일 전송 코드 수정
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberController.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/UpdatePwDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/MemberRepository.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
Labels: 💾 Server, 🔨 Fix

#46 fix: 비밀번호 수정 코드 수정
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberController.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/UpdatePwDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/MemberRepository.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#45 feat/ likes service, controller 구현
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Board.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Reply.java
  src/main/java/com/luckyvicky/woosan/domain/likes/controller/LikesController.java
  src/main/java/com/luckyvicky/woosan/domain/likes/dto/ToggleRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/likes/entity/Likes.java
  src/main/java/com/luckyvicky/woosan/domain/likes/repository/LikesRepository.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesService.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesServiceImpl.java
Labels: 💾 Server, ✨ Feature

#49 fix: 비밀번호 수정 코드 수정
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
Labels: 💾 Server, 🔨 Fix

#50 fix/ writerDTO 삭제
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/ReplyDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/WriterDTO.java
  src/test/java/com/luckyvicky/woosan/service/BoardServiceTest.java
Labels: 💾 Server, 🔨 Fix

#51 feat: 신고 등록 컨트롤러 코드 작성
  src/main/java/com/luckyvicky/woosan/domain/report/controller/ReportController.java
  src/main/java/com/luckyvicky/woosan/domain/report/dto/ReportDTO.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportService.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportServiceImpl.java
  src/test/java/com/luckyvicky/woosan/service/ReportServiceTests.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#52 feat : matcing 정기모임, 번개 작성완료
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MemberMatchingRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoard.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MemberMatching.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MatchingBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MemberMatchingServiceImpl.java
  src/test/java/com/luckyvicky/woosan/repository/MatchingBoardRepositoryTests.java
Labels: 💾 Server, ✨ Feature

#54 fix: 버그 수정
  src/main/java/com/luckyvicky/woosan/domain/report/dto/ReportDTO.java
  src/test/java/com/luckyvicky/woosan/service/ReportServiceTests.java
Labels: 🔨 Fix

#56 feat: matching 리플기능, 셀프소개팅 입력 구현중
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoard.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/MemberProfile.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/MemberType.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/MemberProfileRepository.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/MemberRepository.java
  src/test/java/com/luckyvicky/woosan/repository/MemberMatchingRepositoryTests.java
  src/test/java/com/luckyvicky/woosan/service/MatchingBoardServiceTest.java
  src/test/java/com/luckyvicky/woosan/service/ReplyServiceTest.java
Labels: 💾 Server, ✨ Feature

#55 Roulette DTO, Service, ServiceImpl, Controller 생성
  src/main/java/com/luckyvicky/woosan/domain/member/controller/RouletteController.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/RouletteDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/RouletteService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/RouletteServiceImpl.java
Labels: 💾 Server

#57 fix : 멤버타입 수정 , 멤버리포지토리 임포트 수정
  src/main/java/com/luckyvicky/woosan/domain/member/entity/MemberType.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/MemberRepository.java
Labels: 💾 Server, 🔨 Fix

#58 fix: ReplyServiceTest WriterDTO 이슈 해결
  src/test/java/com/luckyvicky/woosan/service/ReplyServiceTest.java
Labels: 🐞 BugFix

#60 feat: Member entity에 포인트에 따른 레벨 및 포인트 변화 추가
  src/main/java/com/luckyvicky/woosan/domain/member/entity/Member.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
  src/test/java/com/luckyvicky/woosan/repository/MatchingBoardRepositoryTests.java
  src/test/java/com/luckyvicky/woosan/repository/MemberRepositoryTests.java
Labels: 💾 Server, ✨ Feature, 🔨 Fix

#61 fix: 신고 api 수정
  src/main/java/com/luckyvicky/woosan/domain/report/controller/ReportController.java
  src/main/java/com/luckyvicky/woosan/domain/report/mapper/ReportMapper.java
  src/main/java/com/luckyvicky/woosan/domain/report/repository/ReportRepository.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportService.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportServiceImpl.java
Labels: 📬 API, 🔨 Fix
