Repository LuckyVickys/woosan-back, pull requests merged in 2024-07, with the labels that each got.

#62 feat: globalException 작성
  src/main/java/com/luckyvicky/woosan/global/exception/ErrorCode.java
  src/main/java/com/luckyvicky/woosan/global/exception/ExceptionResponse.java
  src/main/java/com/luckyvicky/woosan/global/exception/GlobalException.java
  src/main/java/com/luckyvicky/woosan/global/exception/GlobalizedResponseException.java
Labels: 💾 Server, ✨ Feature

#63 feat/ 댓글 exception 추가
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/board/exception/BoardNotFoundException.java
  src/main/java/com/luckyvicky/woosan/domain/board/exception/MemberNotFoundException.java
  src/main/java/com/luckyvicky/woosan/domain/board/exception/ReplyNotFoundException.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/test/java/com/luckyvicky/woosan/repository/BoardRepositoryTest.java
  src/test/java/com/luckyvicky/woosan/service/BoardServiceTest.java
Labels: 💾 Server, ✨ Feature, 🔨 Fix

#64 feat: validationBoardId 작성
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
Labels: 💾 Server, ✨ Feature

#65 fix: validationBoardId 작성
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
Labels: 🔨 Fix

#66 feat: 기존 session 로그인 코드 삭제하고 security, jwt 관련 코드 작성
  build.gradle
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberController.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/LoginReqDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/auth/dto/CustomUserDetails.java
  src/main/java/com/luckyvicky/woosan/global/auth/filter/JWTUtil.java
  src/main/java/com/luckyvicky/woosan/global/auth/filter/LoginFilter.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/CustomUserDetailsService.java
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
Labels: 💾 Server, ✨ Feature

#68 Feat/cors mvc config
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
Labels: 💾 Server, ✨ Feature, 🔨 Fix

#69 fix: 프론트 작업을 위해 setAllowedOrigins에서 setAllowedOriginPatterns으로 변경
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#71 fix: Reply getRegDate() 수정
  src/main/java/com/luckyvicky/woosan/domain/board/dto/ReplyDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IReply.java
  src/test/java/com/luckyvicky/woosan/repository/BoardRepositoryTest.java
  src/test/java/com/luckyvicky/woosan/repository/ReplyRepositoryTest.java
Labels: 🐞 BugFix, 💾 Server, 🔨 Fix

#72 fix: Reply content length 255 to 1000
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Reply.java
Labels: 🔨 Fix

#74 feat: multipart file 반영
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
Labels: 📬 API, 🔨 Fix

#73 fix: papago컨트롤러 수정
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
Labels: 🐞 BugFix, 💾 Server, 📬 API

#75 fix: PageRequestDTO, PageResponseDTO util 패키지로 이동
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardPageResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/util/PageRequestDTO.java
  src/main/java/com/luckyvicky/woosan/global/util/PageResponseDTO.java
  src/test/java/com/luckyvicky/woosan/service/ReplyServiceTest.java
Labels: 💾 Server, 🔨 Fix

#76 feat: 사용자별 추천 상태 확인
  src/main/java/com/luckyvicky/woosan/domain/likes/controller/LikesController.java
  src/main/java/com/luckyvicky/woosan/domain/likes/repository/LikesRepository.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesService.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix

#77 feat: message 엔티티, DTO 생성
  src/main/java/com/luckyvicky/woosan/domain/member/repository/MemberRepository.java
  src/main/java/com/luckyvicky/woosan/domain/messages/dto/MessageDTO.java
  src/main/java/com/luckyvicky/woosan/domain/messages/dto/MessagesDTO.java
  src/main/java/com/luckyvicky/woosan/domain/messages/entity/Message.java
  src/main/java/com/luckyvicky/woosan/domain/messages/entity/Messages.java
  src/main/java/com/luckyvicky/woosan/domain/messages/repository/MessageRepository.java
  src/main/java/com/luckyvicky/woosan/domain/messages/repository/MessagesRepository.java
Labels: 💾 Server, ✨ Feature, 🔨 Fix

#79 feat: 게시판 사진 수정 기능
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgService.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API

#83 feat: 게시물 전체 조회 댓글 수 기능
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Board.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Reply.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IBoardMember.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/test/java/com/luckyvicky/woosan/service/ReplyServiceTest.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix, ✅ Test

#84 fix/ReplyException
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
Labels: 💾 Server, 🔨 Fix

#86 Fix/roulette룰렛 돌리면 일정 포인트 달성 시 등업하는 코드 추가
  src/main/java/com/luckyvicky/woosan/domain/member/controller/RouletteController.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/RouletteServiceImpl.java
Labels: 💾 Server

#88 fix: 댓글 부모자식 변경
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Board.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/likes/controller/LikesController.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesServiceImpl.java
  src/test/java/com/luckyvicky/woosan/repository/ReplyRepositoryTest.java
Labels: 💾 Server, 🔨 Fix

#90 feat: 추천 여부 확인 기능
  src/main/java/com/luckyvicky/woosan/domain/likes/repository/LikesRepository.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesService.java
  src/main/java/com/luckyvicky/woosan/domain/member/controller/RouletteController.java
Labels: 🐞 BugFix

#91 Update build.gradle
  build.gradle
Labels: 💾 Server, 🔨 Fix, ⚙ Setting

#94 fix: 댓글 작성, 삭제 수정
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Board.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/likes/controller/LikesController.java
  src/main/java/com/luckyvicky/woosan/domain/likes/dto/LikesDTO.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesServiceImpl.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#95 feat: clova summary 이용해서 게시글 상세 페이지 세 줄 요약 기능 구현
  build.gradle
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/SummaryService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/SummaryServiceImpl.java
Labels: 💾 Server, ✨ Feature

#96 fix/ Roulette2 수정
  src/main/java/com/luckyvicky/woosan/domain/member/controller/RouletteController.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/RouletteServiceImpl.java
Labels: 🔨 Fix

#97 feat/MyPageProfileUpdate 프로필 수정기능 생성
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberProfileController.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/ProfileUpdateDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/Member.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/MemberProfile.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberProfileService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberProfileServiceImpl.java
Labels: 💾 Server

#100 feat/ReadboardMyPage 마이페이지에서 내가 쓴 게시글 조회기능 추가
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/WriterDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
Labels: 💾 Server

#102 fix: gitignore 변경
  .gitignore
Labels: 💾 Server, ⚙ Setting

#104 feat: board기능 예외처리
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Board.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Reply.java
  src/main/java/com/luckyvicky/woosan/domain/board/exception/BoardException.java
  src/main/java/com/luckyvicky/woosan/domain/board/exception/ReplyException.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/likes/exception/LikeException.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/exception/ErrorCode.java
  src/main/java/com/luckyvicky/woosan/global/util/PageRequestDTO.java
Labels: 🐞 BugFix, 💾 Server, 🔨 Fix

#105 feat: cs페이지 공지사항
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix

#106 feat: cors 설정 완료
  src/main/java/com/luckyvicky/woosan/global/config/CorsMvcConfig.java
Labels: 💾 Server, ⚙ Setting

#107 fix: 권한 설정
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
Labels: 💾 Server, 📬 API, ⚙ Setting

#108 fix: refresh, accessToken 발급 완료
  src/main/java/com/luckyvicky/woosan/domain/member/dto/LoginResponseDTO.java
  src/main/java/com/luckyvicky/woosan/global/auth/controller/AuthController.java
  src/main/java/com/luckyvicky/woosan/global/auth/dto/CustomUserInfoDTO.java
  src/main/java/com/luckyvicky/woosan/global/auth/filter/JWTUtil.java
  src/main/java/com/luckyvicky/woosan/global/auth/filter/JwtAuthFilter.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthService.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
Labels: 💾 Server, 📬 API, 🔨 Fix, ⚙ Setting

#109 feat: 게시판, 댓글 작성자 프로필
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/ReplyDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API

#114 feat: 회원 정보를 저장할 redis 설정
  build.gradle
  src/main/resources/application.properties
Labels: 💾 Server, ✨ Feature, 📬 API

#113 feat: 카카오 회원가입, 로그인 구현
  src/main/java/com/luckyvicky/woosan/global/auth/controller/SocialController.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthService.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API

#110 fix/ReadboardMyPage 마이페이지에서 내가 쓴 게시글 조회기능 패키지 이동
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MypageController.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
Labels: 🔨 Fix

#115 fix: 메시지 default값 저장되도록 수정
  src/main/java/com/luckyvicky/woosan/domain/messages/controller/MessageController.java
  src/main/java/com/luckyvicky/woosan/domain/messages/dto/MessageAddDTO.java
  src/main/java/com/luckyvicky/woosan/domain/messages/service/MessageServiceImpl.java
  src/main/resources/application.properties
Labels: 💾 Server, 🔨 Fix

#116 feat: 멤버 프로필 사진 클릭 시 멤버 정보 뜨게
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberController.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/MemberInfoDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/mapper/MemberMapper.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API

#120 feat: 검색기능 1차 구현
  src/main/java/com/luckyvicky/woosan/WoosanApplication.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix, ⚙ Setting

#119 feat: 검색 자동 완성 기능(보완 필요)
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/elasticsearch/ElasticsearchBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API

#117 matchingBoardDTO 누락 수정함
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MatchingBoardReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardResponseDTO.java
Labels: 💾 Server, 🔨 Fix

#118 feat: refreshToken 이용해서 accessToken 재발급 받는 방식 변경, accessToken 유효 시간 변경, 토큰 관련 예외 처리
  src/main/java/com/luckyvicky/woosan/domain/member/dto/LoginResponseDTO.java
  src/main/java/com/luckyvicky/woosan/global/auth/controller/AuthController.java
  src/main/java/com/luckyvicky/woosan/global/auth/dto/RefreshTokenReqDTO.java
  src/main/java/com/luckyvicky/woosan/global/auth/dto/RefreshTokenResDTO.java
  src/main/java/com/luckyvicky/woosan/global/auth/exception/JWTException.java
  src/main/java/com/luckyvicky/woosan/global/auth/filter/JwtAuthFilter.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthService.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/exception/ErrorCode.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix

#122 fix: 엘라스틱서치 머지 후 매칭 삭제 이슈 해결
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MatchingBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MemberMatchingController.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardReplyRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardReplyResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MemberMatchingRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MemberMatchingResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoard.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoardReply.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MemberMatching.java
  src/main/java/com/luckyvicky/woosan/domain/matching/mapper/MatchingBoardMapper.java
  src/main/java/com/luckyvicky/woosan/domain/matching/mapper/MatchingBoardReplyMapper.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MatchingBoardReplyRepository.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MatchingBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MemberMatchingRepository.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MemberMatchingRepositoryCustom.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MemberMatchingRepositoryCustomImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardReplyService.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MemberMatchingService.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MemberMatchingServiceImpl.java
Labels: 🐞 BugFix

#123 fix: merge 오류 수정
  src/main/java/com/luckyvicky/woosan/WoosanApplication.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
Labels: 🔨 Fix

#124 fix: member의 id 추가
  src/main/java/com/luckyvicky/woosan/domain/member/dto/MemberInfoDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
Labels: 💾 Server, 🔨 Fix

#125 Feat/auto keyword
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/elasticsearch/ElasticsearchBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix

#126 fix: member의 id 추가, email로 user 정보 가져올 수 있게 수정
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberController.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#127 fix: 로그인 후 반환 값 변경
  src/main/java/com/luckyvicky/woosan/domain/member/dto/LoginResponseDTO.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthServiceImpl.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#128 Feat/keyword prefix
  src/main/java/com/luckyvicky/woosan/domain/board/repository/elasticsearch/ElasticsearchBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 💾 Server, 📬 API

#129 Feat/synonym search
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Board.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#130 feat: elasticsearch 초성 검색 기능 구현 완료, 유의어 검색 기능 구현중
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Board.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/elasticsearch/ElasticsearchBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
  src/test/java/com/luckyvicky/woosan/service/ReplyServiceTest.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix, ⚙ Setting

#131 fix: 소셜 로그인 반환 값 변경
  src/main/java/com/luckyvicky/woosan/global/auth/controller/SocialController.java
  src/main/java/com/luckyvicky/woosan/global/auth/dto/CustomUserInfoDTO.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthServiceImpl.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#132 fix: 유의어 검색 구현 완료
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 🐞 BugFix, 💾 Server, ✨ Feature, 🔨 Fix

#133 feat : 실시간 검색 순위 구현
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/SearchKeyword.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/elasticsearch/SearchKeywordRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix

#134 Feat/search paging
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/SearchDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/SearchPageResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/elasticsearch/ElasticsearchBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 🐞 BugFix, 💾 Server, ✨ Feature, 📬 API, 🔨 Fix

#137 feat: 띄어쓰기 포함해서 키워드 추천, 댓글 작성 수정
  src/main/java/com/luckyvicky/woosan/domain/board/repository/elasticsearch/ElasticsearchBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
Labels: 📬 API

#142 feat:내가 작성한 댓글
  src/main/java/com/luckyvicky/woosan/domain/board/dto/MyReplyDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/BoardInfo.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IMyReply.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/jpa/ReplyRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MypageController.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix

#143 feat: 내가 작성한 게시물
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IMyBoard.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/jpa/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/jpa/ReplyRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MypageController.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/MyBoardDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/MyPageDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/MyReplyDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
  src/test/java/com/luckyvicky/woosan/repository/MatchingBoardReplyRepositoryTests.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix

#144 feat: 내가 좋아요 한 게시글
  src/main/java/com/luckyvicky/woosan/domain/board/repository/jpa/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MypageController.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API

#145 Fix/my pages
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MypageController.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
Labels: 🐞 BugFix, 🔨 Fix

#146 feat/ 관리자 공지사항 crud 서비스, 컨트롤러
  src/main/java/com/luckyvicky/woosan/domain/admin/controller/AdminController.java
  src/main/java/com/luckyvicky/woosan/domain/admin/service/AdminService.java
  src/main/java/com/luckyvicky/woosan/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/MyBoardDTO.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix

#147 fix: 재발급 받은 비밀번호 해시화
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
Labels: 💾 Server, 🔨 Fix

#148 feat: 관리자 등록된 신고 기능
  src/main/java/com/luckyvicky/woosan/domain/admin/controller/AdminController.java
  src/main/java/com/luckyvicky/woosan/domain/report/controller/ReportController.java
  src/main/java/com/luckyvicky/woosan/domain/report/entity/Report.java
  src/main/java/com/luckyvicky/woosan/domain/report/repository/ReportRepository.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportService.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
Labels: 📬 API

#149 feat: message list 보낸 쪽지함, 받은 쪽지함
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MypageController.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/messages/dto/MessageDTO.java
  src/main/java/com/luckyvicky/woosan/domain/messages/repository/MessageRepository.java
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
Labels: 💾 Server, ✨ Feature, 📬 API

#152 feat: 검색순위 기준 사건 대비 상승 하락 반영
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/RankingDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 💾 Server, ✨ Feature, 💻 Client, 📬 API, 🔨 Fix

#153 feat: 프로필 수정 및 등록
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberProfileController.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/ProfileUpdateDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/MemberProfileRepository.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberProfileService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberProfileServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API

#154 fix: 게시물, 댓글 로그인한 사용자 only 삭제 처리
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/RemoveDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/test/java/com/luckyvicky/woosan/service/ReplyServiceTest.java
Labels: 🐞 BugFix, 💾 Server, 📬 API, 🔨 Fix

#155 fix: 카카오 회원 닉네임 중복 방지
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MypageController.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthServiceImpl.java
Labels: 🐞 BugFix, 💾 Server, 🔨 Fix

#156 fix: 실시간 검색어 순위 오류 해결
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 🐞 BugFix, 📬 API, 🔨 Fix

#157 feat: 사용자 정보 프로필 추가
  src/main/java/com/luckyvicky/woosan/domain/member/dto/MemberInfoDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#158 fix : 매칭댓글 답글 수정
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MatchingBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MatchingBoardReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MemberMatchingController.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardReplyRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardReplyResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MemberMatchingRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MemberMatchingResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoard.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoardReply.java
  src/main/java/com/luckyvicky/woosan/domain/matching/mapper/MatchingBoardMapper.java
  src/main/java/com/luckyvicky/woosan/domain/matching/mapper/MatchingBoardReplyMapper.java
  src/main/java/com/luckyvicky/woosan/domain/matching/mapper/MemberMatchingMapper.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MatchingBoardReplyRepository.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MatchingBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MemberMatchingRepository.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MemberMatchingRepositoryCustom.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MemberMatchingRepositoryCustomImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardReplyService.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MemberMatchingService.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MemberMatchingServiceImpl.java
Labels: 💾 Server, ✨ Feature, 🔨 Fix

#159 feat: DTO 프론트에서 int형 null값 허용하도록 수정
  src/main/java/com/luckyvicky/woosan/domain/member/dto/ProfileUpdateDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberProfileServiceImpl.java
Labels: 🔨 Fix

#160 매칭 닉네임 프로필 이미지 구현
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/mapper/MatchingBoardMapper.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardServiceImpl.java
Labels: 💾 Server, ✨ Feature

#161 fix: 게시판 수정 시 한글 사진 파일 삭제되도록 수정
  src/main/java/com/luckyvicky/woosan/domain/admin/controller/AdminController.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgServiceImpl.java
Labels: 🐞 BugFix, 💾 Server, 🔨 Fix

#162 나의 매칭 상세 페이지구현
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardReplyResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MemberMatchingResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/mapper/MatchingBoardReplyMapper.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MemberMatchingServiceImpl.java
Labels: 💾 Server, ✨ Feature, 🔨 Fix

#163 fix: papagoService, summaryService를 aiService로 합치고 공통으로 쓰이는 메소드 추출
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/AIService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/AIServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/PapagoService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/PapagoServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/SummaryServiceImpl.java
Labels: 💾 Server, 📬 API, 📦 refactoring

#166 feat: redis config 수정
  src/main/java/com/luckyvicky/woosan/global/config/RedisConfig.java
  src/main/resources/application.properties
Labels: 💾 Server, 🔨 Fix, ⚙ Setting

#168 fix: redis에 RefreshToken 저장 및 로그인 결과 DTO 변경
  src/main/java/com/luckyvicky/woosan/domain/member/dto/LoginResponseDTO.java
  src/main/java/com/luckyvicky/woosan/global/auth/controller/AuthController.java
  src/main/java/com/luckyvicky/woosan/global/auth/dto/CustomUserInfoDTO.java
  src/main/java/com/luckyvicky/woosan/global/auth/entity/RefreshToken.java
  src/main/java/com/luckyvicky/woosan/global/auth/filter/JWTUtil.java
  src/main/java/com/luckyvicky/woosan/global/auth/repository/RefreshTokenRepository.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthService.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/RedisService.java
Labels: 💾 Server, ✨ Feature, 📬 API, 📦 refactoring

#167 refactor: 게시판 리팩토링
  src/main/java/com/luckyvicky/woosan/domain/admin/controller/AdminController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardListDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardPageResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Board.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IBoard.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IBoardList.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/jpa/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/util/Constants.java
  src/main/java/com/luckyvicky/woosan/domain/board/util/Validate.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/config/RootConfig.java
  src/main/java/com/luckyvicky/woosan/global/util/CommonUtils.java
Labels: 🔨 Fix

#169 feat: 관리자 배너 업로드 및 삭제 & 신고 체크 및 타겟 이동(게시판)
  src/main/java/com/luckyvicky/woosan/domain/admin/controller/AdminController.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/dto/FileUpdateDTO.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgService.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/report/dto/TargetDTO.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportService.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API

#170 fix: 로그인 반환 값 변경
  src/main/java/com/luckyvicky/woosan/domain/member/dto/LoginResponseDTO.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthServiceImpl.java
Labels: 🐞 BugFix, 💾 Server, 🔨 Fix

#171 refactor: board, reply, es 리팩토링
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/SearchDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/WriterDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/util/Constants.java
  src/main/java/com/luckyvicky/woosan/domain/board/util/Validate.java
  src/main/java/com/luckyvicky/woosan/global/util/CommonUtils.java
  src/main/java/com/luckyvicky/woosan/global/util/Constants.java
  src/main/java/com/luckyvicky/woosan/global/util/ValidationHelper.java
  src/main/resources/elastic/board-mapping.json
  src/main/resources/elastic/board-setting.json
  src/test/java/com/luckyvicky/woosan/service/BoardServiceTest.java
  src/test/java/com/luckyvicky/woosan/service/ReplyServiceTest.java
Labels: 💾 Server, 📦 refactoring

#172 refactor: like
  src/main/java/com/luckyvicky/woosan/domain/likes/controller/LikesController.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesServiceImpl.java
Labels: 💾 Server, 📦 refactoring

#173 refactor: 관리자, 마이페이지
  src/main/java/com/luckyvicky/woosan/domain/admin/controller/AdminController.java
  src/main/java/com/luckyvicky/woosan/domain/admin/service/AdminService.java
  src/main/java/com/luckyvicky/woosan/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
Labels: 📦 refactoring

#174 feat: 신고 쪽지 추가
  src/main/java/com/luckyvicky/woosan/domain/admin/controller/AdminController.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportService.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportServiceImpl.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#177 refactor: 파일 이미지, 신고 리펙토링
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/utils/FileImgUtils.java
  src/main/java/com/luckyvicky/woosan/domain/report/controller/ReportController.java
  src/main/java/com/luckyvicky/woosan/domain/report/repository/ReportRepository.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportService.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/report/utils/ReportServiceUtil.java
  src/main/java/com/luckyvicky/woosan/global/config/ObjectStorageConfig.java
  src/main/java/com/luckyvicky/woosan/global/util/TargetType.java
Labels: 💾 Server, 🔨 Fix, 📦 refactoring

#178 feat: redis를 활용한 회원가입 코드를 위한 JoinCode entity, JoinCodeRepository 생성
  src/main/java/com/luckyvicky/woosan/domain/member/entity/JoinCode.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/JoinCodeRepository.java
  src/main/java/com/luckyvicky/woosan/global/auth/entity/RefreshToken.java
Labels: 💾 Server, ✨ Feature

#182 fix: modelattribute to requestPart
  src/main/java/com/luckyvicky/woosan/domain/admin/controller/AdminController.java
  src/main/java/com/luckyvicky/woosan/domain/admin/service/AdminService.java
  src/main/java/com/luckyvicky/woosan/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/test/java/com/luckyvicky/woosan/service/BoardServiceTest.java
  src/test/java/com/luckyvicky/woosan/service/ReplyServiceTest.java
Labels: 🔨 Fix, 📦 refactoring

#183 fix: es 명명 메서드 to NativeSearchQueryBuilder
  src/main/java/com/luckyvicky/woosan/domain/board/repository/elasticsearch/ElasticsearchBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
  src/test/java/com/luckyvicky/woosan/service/PapagoServiceImpl.java
Labels: 🔨 Fix, 📦 refactoring

#184 fix: 쪽지 정보 수정
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
Labels: 🐞 BugFix, 💾 Server, 🔨 Fix

#185 refactor: 회원 프로필 리펙토링 및 한줄소개 추가
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberProfileController.java
  src/main/java/com/luckyvicky/woosan/domain/member/dto/ProfileUpdateDTO.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/MemberProfile.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberProfileService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberProfileServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/utils/MemberProfileUtil.java
  src/main/java/com/luckyvicky/woosan/domain/member/utils/ProfileUpdateMapper.java
  src/main/java/com/luckyvicky/woosan/domain/report/utils/ReportServiceUtil.java
Labels: 💾 Server, 📦 refactoring

#186 fix: board, reply 컨트롤러 엔드포인트 추가
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ReplyController.java
Labels: 🐞 BugFix, 🔨 Fix

#187 fix: MainNotice10to5
  src/main/java/com/luckyvicky/woosan/domain/board/repository/jpa/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
Labels: 🔨 Fix

#188 메인페이지에 뉴매칭리스트 구현
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MatchingBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MatchingBoardReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MemberMatchingController.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardReplyRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoard.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoardReply.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MatchingBoardReplyRepository.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardReplyService.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MemberMatchingServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API

#189 fix: 레디스 레포지토리 명시
  src/main/java/com/luckyvicky/woosan/WoosanApplication.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MemberMatchingServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberController.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/jpa/MemberProfileRepository.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/jpa/MemberRepository.java
  src/main/java/com/luckyvicky/woosan/domain/member/repository/redis/JoinCodeRepository.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberProfileServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/RouletteServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/utils/MemberProfileUtil.java
  src/main/java/com/luckyvicky/woosan/domain/messages/service/MessageServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/auth/filter/JwtAuthFilter.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/CustomUserDetailsService.java
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
  src/main/java/com/luckyvicky/woosan/global/config/RedisConfig.java
  src/main/java/com/luckyvicky/woosan/global/util/ValidationHelper.java
  src/test/java/com/luckyvicky/woosan/repository/BoardRepositoryTest.java
  src/test/java/com/luckyvicky/woosan/repository/JoinCodeRepositoryTests.java
  src/test/java/com/luckyvicky/woosan/repository/MatchingBoardRepositoryTests.java
  src/test/java/com/luckyvicky/woosan/repository/MemberMatchingRepositoryTests.java
  src/test/java/com/luckyvicky/woosan/repository/MemberRepositoryTests.java
  src/test/java/com/luckyvicky/woosan/repository/MessageRepositoryTests.java
  src/test/java/com/luckyvicky/woosan/repository/ReplyRepositoryTest.java
  src/test/java/com/luckyvicky/woosan/repository/ReportRepositoryTests.java
  src/test/java/com/luckyvicky/woosan/service/BoardServiceTest.java
  src/test/java/com/luckyvicky/woosan/service/MatchingBoardServiceTest.java
  src/test/java/com/luckyvicky/woosan/service/ReplyServiceTest.java
Labels: 💾 Server, ⚙ Setting

#190 fix: 주석, 로그 정리
  src/main/java/com/luckyvicky/woosan/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ReplyController.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/Board.java
  src/main/java/com/luckyvicky/woosan/domain/board/entity/SearchKeyword.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IReply.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/elasticsearch/ElasticsearchBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/jpa/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/jpa/ReplyRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/likes/repository/LikesRepository.java
  src/main/java/com/luckyvicky/woosan/global/auth/repository/RefreshTokenRepository.java
  src/main/java/com/luckyvicky/woosan/global/util/HashUtil.java
Labels: 🔨 Fix

#191 fix: 필요없는 파일, 코드 삭제
  src/main/java/com/luckyvicky/woosan/WoosanApplication.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/controller/FileImgController.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgService.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberProfileService.java
Labels: 🔨 Fix

#192 refactor: likesServiceImpl 모듈화
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesServiceImpl.java
Labels: 💾 Server, 📦 refactoring

#193 fix: 오류 수정
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/controller/MemberProfileController.java
Labels: 🐞 BugFix

#194 fix: 로그인 반환값 수정
  src/main/java/com/luckyvicky/woosan/domain/member/dto/LoginResponseDTO.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/AuthServiceImpl.java
Labels: 💾 Server, 🔨 Fix

#195 refactor: 수정 페이지 조회 프로젝션 적용 및 DTO 변경, AiService DTO 변경
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardApiDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/UpdateBoardDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/projection/IUpdateBoard.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/AIService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/AIServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
Labels: 💾 Server, 📬 API, 📦 refactoring

#196 feat&fix: SecurityJWT 오류 수정, Authority에 레벨 추가
  src/main/java/com/luckyvicky/woosan/global/auth/dto/CustomUserDetails.java
  src/main/java/com/luckyvicky/woosan/global/auth/filter/JWTUtil.java
  src/main/java/com/luckyvicky/woosan/global/auth/filter/JwtAuthFilter.java
Labels: 🐞 BugFix, 💾 Server, 🔨 Fix

#198 feat: 일별 조회수 별 상위 7개 인기글 , 연관 게시물 8 기능 구현
  src/main/java/com/luckyvicky/woosan/domain/admin/controller/AdminController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/controller/ElasticsearchBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/BoardDetailDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/DailyBestBoardDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/dto/SuggestedBoardDTO.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 💾 Server, ✨ Feature, 📬 API, 🔨 Fix

#200 feat: getBoard/getNotice 분리
  src/main/java/com/luckyvicky/woosan/domain/board/controller/BoardController.java
  src/main/java/com/luckyvicky/woosan/domain/board/repository/jpa/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/util/ValidationHelper.java
Labels: 🐞 BugFix, 💾 Server, 📬 API, 🔨 Fix

#201 del: 사용하지 않는 createPageable 메소드 삭제
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
Labels: 💾 Server, 🔨 Fix

#203 fix:작성일 추가
  src/main/java/com/luckyvicky/woosan/domain/board/dto/SuggestedBoardDTO.java
Labels: 🔨 Fix

#204 fix: 연관게시물조회 현재 게시물과 동일한 게시물 제안 수정
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ElasticsearchBoardServiceImpl.java
Labels: 💾 Server, 🔨 Fix, 📦 refactoring

#206 모임 생성시 레벨제한 , 디버깅 콘솔 삭제
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MatchingBoardController.java
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MemberMatchingController.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoard.java
  src/main/java/com/luckyvicky/woosan/domain/matching/entity/MatchingBoardReply.java
  src/main/java/com/luckyvicky/woosan/domain/matching/exception/MatchingException.java
  src/main/java/com/luckyvicky/woosan/domain/matching/mapper/MatchingBoardReplyMapper.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MatchingBoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardService.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MemberMatchingServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/entity/MemberProfile.java
Labels: 💾 Server, 🔨 Fix

#207 매칭 api 중복부분 수정
  src/main/java/com/luckyvicky/woosan/domain/matching/controller/MatchingBoardController.java
Labels: 🔨 Fix

#208 feat: securityconfig
  src/main/java/com/luckyvicky/woosan/global/auth/filter/JWTUtil.java
  src/main/java/com/luckyvicky/woosan/global/auth/filter/JwtAuthFilter.java
  src/main/java/com/luckyvicky/woosan/global/auth/service/RedisService.java
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
Labels: 💾 Server, ✨ Feature, 💻 Client, ⚙ Setting

#209 fix: securityconfig
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
Labels: 💾 Server

#210 feat: Slave DB 요청 구분
  src/main/java/com/luckyvicky/woosan/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/ReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/fileImg/service/FileImgServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/likes/service/LikesServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberProfileServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MemberServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/member/service/MyPageServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/report/service/ReportServiceImpl.java
  src/main/java/com/luckyvicky/woosan/global/annotation/SlaveDBRequest.java
  src/main/java/com/luckyvicky/woosan/global/aop/DataSourceAspect.java
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
  src/main/java/com/luckyvicky/woosan/global/config/distinct/DataSourceConfiguration.java
  src/main/java/com/luckyvicky/woosan/global/config/distinct/DataSourceContextHolder.java
  src/main/java/com/luckyvicky/woosan/global/config/distinct/RoutingDataSource.java
  src/main/java/com/luckyvicky/woosan/global/config/distinct/TransactionConfig.java
Labels: 💾 Server, ✨ Feature, 🔨 Fix

#211 fix: 주석 삭제
  src/main/java/com/luckyvicky/woosan/global/aop/DataSourceAspect.java
Labels: 🔨 Fix

#213 fix: matching 부분 securityconfig 수정
  src/main/java/com/luckyvicky/woosan/global/config/CustomSecurityConfig.java
Labels: 🐞 BugFix, 💾 Server, 🔨 Fix

#215 Fix/new matching
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardRequestDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/dto/MatchingBoardResponseDTO.java
  src/main/java/com/luckyvicky/woosan/domain/matching/repository/MatchingBoardReplyRepository.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardReplyServiceImpl.java
  src/main/java/com/luckyvicky/woosan/domain/matching/service/MatchingBoardServiceImpl.java
Labels: 💾 Server, 📬 API, 🔨 Fix

#216 fix: 게시물 전체 조회 날짜순 정렬 수정
  src/main/java/com/luckyvicky/woosan/domain/board/repository/jpa/BoardRepository.java
  src/main/java/com/luckyvicky/woosan/domain/board/service/BoardServiceImpl.java
Labels: 🔨 Fix
